---
title: "R Notebook"
output:
  html_notebook:
    toc: TRUE
    toc_float: TRUE
---



```{r,echo = F, warnings = F}
library(data.table)
library(causl)


masks<-function(formulas, family = rep(1, nc), wh, LHS)
{
  if (is.list(family)) {
    ncop <- lengths(family[length(family)])
    family <- unlist(family[-length(family)])
  }
  formulas <- unlist(formulas)
  nc <- length(formulas) + ncop - 1
  beta_m <- matrix(0, nrow = max(unlist(wh)), ncol = nc)
  phi_m <- numeric(length(family))
  for (i in seq_along(phi_m)) {
    if (family[i] >= 1 && family[i] <= 3) {
      phi_m[i] <- 1
    }
    beta_m[wh[[i]], i] <- 1
  }

  cp <- length(phi_m) +1
  for (i in seq_len(ncop)){
    beta_m[wh[[cp]], length(phi_m) + i] <- 1

  }
  return(list(beta_m = beta_m, phi_m = phi_m))
}
```

# bivariate copula

## n_data  = 250
```{r}
forms_exp <- list(Z ~ C1*C2,
                  list(X ~ C1*C2, C1~ 1, C2 ~ 1),
                  Y ~ X*C1*C2,
                  ~ X*C1*C2  #copula
)


# parameters
pars_exp <- list(C1 = list(beta = 0.5),
                 C2 = list(beta = 2,phi = 1),
                 Z = list(beta = c(0.2,0.6,0.9,0.3),phi = 1),
                 X = list(beta = c(0.3,0.8,0.2,0.1)),
                 Y = list(beta = c(0.6,0.8 ,0.2,0.3,0,0,0,0),phi = 1),
                 cop = list(beta = matrix(c(1,0,0,0,0,0,0,0),nrow = 8)))

data_exp <- setDT(causalSamp(250,formulas = forms_exp, pars = pars_exp, family = list(1,c(5,5,1),1,1)))
## get param masks
forms2_exp <- causl:::tidy_formulas(forms_exp[-2], kwd = "cop")
full_form_exp <- causl:::merge_formulas(forms2_exp)
wh_exp <- full_form_exp$wh
# LHS <- lhs(forms2[-length(forms2)])
msks_exp <- masks(forms_exp[-2],family = list(1,1,1),wh_exp)

## get model matrix
mm_exp <- model.matrix(full_form_exp$formula, data = data_exp)

theta_exp <- causl:::theta(pars = pars_exp, formulas = forms_exp[-2], full_form_exp, kwd = "cop")

msks2 <- copy(msks_exp)
np <- sum(msks2$beta_m > 0)
msks2$beta_m[msks_exp$beta_m > 0] <- theta_exp[seq_len(np)]
msks2$phi_m[msks_exp$phi_m > 0] <- theta_exp[-seq_len(np)]


microbenchmark(
  llC_par <- llC(data_exp[,c(1,5)],mm = mm_exp ,beta = msks2$beta_m,msks2$phi_m,c(1,2)),
  targ<-causl:::ll(data_exp[,c(1,5)],mm = mm_exp ,beta = msks2$beta_m,phi = msks2$phi_m,inCop = c(1,2),fam_cop = 1, family = list(1,1))
  
)

sum(llC_par) == sum(targ)
```
