# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib ManyData
NULL

g <- function(n) {
    .Call('_ManyData_g', PACKAGE = 'ManyData', n)
}

dGcop <- function(x, sigma, logd = FALSE) {
    .Call('_ManyData_dGcop', PACKAGE = 'ManyData', x, sigma, logd)
}

dGcop_sig <- function(x, sigma, logd = FALSE) {
    .Call('_ManyData_dGcop_sig', PACKAGE = 'ManyData', x, sigma, logd)
}

#' @useDynLib ManyData
#' @import RcppArmadillo causl
NULL

expitC <- function(x) {
    .Call('_ManyData_expitC', PACKAGE = 'ManyData', x)
}

createSig <- function(ncv, n, par) {
    .Call('_ManyData_createSig', PACKAGE = 'ManyData', ncv, n, par)
}

qnormC <- function(x) {
    .Call('_ManyData_qnormC', PACKAGE = 'ManyData', x)
}

#' @export
llC <- function(dat, mm, beta, phi, inCop) {
    .Call('_ManyData_llC', PACKAGE = 'ManyData', dat, mm, beta, phi, inCop)
}

qnormC2 <- function(x) {
    .Call('_ManyData_qnormC2', PACKAGE = 'ManyData', x)
}

qnormC3 <- function(x) {
    .Call('_ManyData_qnormC3', PACKAGE = 'ManyData', x)
}

qnormC4 <- function(x) {
    .Call('_ManyData_qnormC4', PACKAGE = 'ManyData', x)
}

createSig2 <- function(ncv, n, par) {
    .Call('_ManyData_createSig2', PACKAGE = 'ManyData', ncv, n, par)
}

#' @useDynLib ManyData
#' @import Rcpp
#' @export
univarDensC <- function(x, eta, phi, link = "missing", family = 1L, df = 50L) {
    .Call('_ManyData_univarDensC', PACKAGE = 'ManyData', x, eta, phi, link, family, df)
}

