# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f2 <- function(x, eta, phi, link = "missing", family = 1L, df = 50L) {
    .Call('_ManyData_f2', PACKAGE = 'ManyData', x, eta, phi, link, family, df)
}

#' @export
univarDensC <- function(x, eta, phi, link = "missing", family = 1L, df = 50L) {
    .Call('_ManyData_univarDensC', PACKAGE = 'ManyData', x, eta, phi, link, family, df)
}

