# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib ManyData
NULL

g <- function(n) {
    .Call('_ManyData_g', PACKAGE = 'ManyData', n)
}

dGcop <- function(x, sigma, logd = FALSE) {
    .Call('_ManyData_dGcop', PACKAGE = 'ManyData', x, sigma, logd)
}

#' @export
dGcop_sig <- function(x, sigma, logd = FALSE) {
    .Call('_ManyData_dGcop_sig', PACKAGE = 'ManyData', x, sigma, logd)
}

#' @useDynLib ManyData
#' @import RcppArmadillo causl
NULL

expitC <- function(x) {
    .Call('_ManyData_expitC', PACKAGE = 'ManyData', x)
}

createSig <- function(ncv, n, par) {
    .Call('_ManyData_createSig', PACKAGE = 'ManyData', ncv, n, par)
}

qnormC <- function(x) {
    .Call('_ManyData_qnormC', PACKAGE = 'ManyData', x)
}

#' @export
llC <- function(dat, mm, beta, phi, inCop) {
    .Call('_ManyData_llC', PACKAGE = 'ManyData', dat, mm, beta, phi, inCop)
}

#' @export
postll_C <- function(current_val, inCop, dat_exp, theta_exp, mm_exp, mask_exp, dat_obs, theta_obs, mm_obs, mask_obs, p_mu, p_sigma, eta) {
    .Call('_ManyData_postll_C', PACKAGE = 'ManyData', current_val, inCop, dat_exp, theta_exp, mm_exp, mask_exp, dat_obs, theta_obs, mm_obs, mask_obs, p_mu, p_sigma, eta)
}

MCMCloop_C <- function(n_iter, init_val, sigma, inCop, dat_exp, theta_exp, mm_exp, mask_exp, dat_obs, theta_obs, mm_obs, mask_obs, p_mu, p_sigma, eta) {
    .Call('_ManyData_MCMCloop_C', PACKAGE = 'ManyData', n_iter, init_val, sigma, inCop, dat_exp, theta_exp, mm_exp, mask_exp, dat_obs, theta_obs, mm_obs, mask_obs, p_mu, p_sigma, eta)
}

#' @useDynLib ManyData
#' @import Rcpp
#' @export
univarDensC <- function(x, eta, phi, link = "missing", family = 1L, df = 50L) {
    .Call('_ManyData_univarDensC', PACKAGE = 'ManyData', x, eta, phi, link, family, df)
}

